name: Deploy NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore packages
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Test project
        run: dotnet test --no-build --configuration Release

      - name: Pack project
        run: dotnet pack src/MBUtils.csproj --no-restore --no-build --configuration Release --include-symbols --output ./output

      - name: Push packages
        run: dotnet nuget push ./output/*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ secrets.NUGET_SOURCE_URL }} --skip-duplicate