name: Deploy NuGet Package

on:
  push:
    #tags:
    #  - 'v*'
    branches:
      - release/0.1.0



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET SDK
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 8.0
          export PATH=$PATH:$HOME/.dotnet

      - name: Restore packages
        run: dotnet restore src/MBUtils.csproj

      - name: Build project
        run: dotnet build src/MBUtils.csproj --no-restore --configuration Release

      - name: Pack project
        run: run: dotnet pack src/MBUtils.csproj --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=0.1.0 --output ./output

      - name: Push packages
        run: dotnet nuget push ./output/*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ secrets.NUGET_SOURCE_URL }}